version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.17.2
    environment:
      GO111MODULE: "on"
    working_directory: ~/go/src/github.com/szyn/digdag-go-client
    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: golint $(go list ./...)
      - run: go vet ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  test:
    jobs:
      - test
